<head>
    <meta charset="UTF-8">
    <title><?= $title ?> - Metal in Leipzig</title>
    <meta name="description" content="Kalender zu Metal-Konzerten und Metal-Parties in Leipzig">
    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="referrer" content="no-referrer">
    <link href="style/style.css" rel="stylesheet">
    <link rel="icon" href="img/icon.png" type="image/x-icon">
</head>