[package]
name = "metal-in-leipzig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
twox-hash = "1.6.2"
chrono = "0.4.19"
reqwest = { version = "0.11", features = ["blocking"] }
image = "0.24.1"
serde_json = "1.0"