# This is a basic workflow to help you get started with Actions

name: build page

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '45 7 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install imagemagick
        run: sudo apt-get install -y imagemagick && convert --version

      - name: Cache flyers
        uses: actions/cache@v4
        with:
          path: public/flyer
          key: flyer-${{ steps.date.outputs.date }}

      - uses: actions/cache@v4
        name: Cache Rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build app
        run: cargo build --release

      - name: Run app
        timeout-minutes: 120
        run: cargo run --release

      - name: Minify HTML/CSS/JS
        # uses https://crates.io/crates/minify-html
        run: |
          cargo install --force minhtml \
          && ~/.cargo/bin/minhtml --keep-closing-tags public/index.html public/recht.html public/style/style.css public/js/filter.js

      # https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
